### ISSUE TITLE
1.How to use the unsync ?  

### ISSUE THREAD

**Issue by feiger313** [jijingg/regif#1]
1.How to use the unsync ?  

My operation:
1.  generate a test_regif.xls
2. set Bus and HW clk = unsync

**ERROR:**
Static check .....
Static check Pass!

Dynamic check .....
Dynamic check Pass!

Traceback (most recent call last):
  File "regif.py", line 1191, in <module>
    regif.genverilog()
  File "regif.py", line 1059, in genverilog
    bmi_io, write_part, iodeclars, vdeclars, wdeclars, instports, defines, undefines, read_part = self.gen_segment()
  File "regif.py", line 1039, in gen_segment
    write_part += reg.write
  File "regif.py", line 295, in write
    return self.fields.w_block()
  File "regif.py", line 546, in w_block
    cdc_part = self.cdc_sync_part_L2()
  File "regif.py", line 539, in cdc_sync_part_L2
    return CDC_PART_L2.format(**locals()) if self.sync_list else ""
KeyError: 'always_ff_begin'

**Comment by jijingg** [comment]
@feiger313 The unsync mode has expired, originally to address bus_clk and hw_clk with unsync,  and now we find the unsync is not unusually and is not necessary. Therefore, the async-mode  will be removed in the next-version,  sync-mode is enough

**Comment by feiger313** [comment]
Thank you for your reply
